version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
    - image: cirrusci/flutter
    steps:
    - checkout
    - run: flutter --version
    - run: flutter pub global activate melos
    - run: melos --version
    - run: melos bootstrap
    - run: melos run test
    - run: melos run gen_coverage
    - codecov/upload:
        file: coverage_report/lcov.info
