version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
    - image: cirrusci/flutter
    resource_class: large
    steps:
    - checkout
    - run: flutter --version
    - run:
        name: Set up environment
        command: |
          echo 'export PATH=$HOME/.pub-cache/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Setup melos
        command: |
          flutter pub global activate melos
          melos --version
          melos bootstrap
    - run: melos run test
    - run: melos run gen_coverage
    - codecov/upload:
        file: coverage_report/lcov.info
